### ISSUE TITLE
Index from home

### ISSUE THREAD

**Issue by KevinNitroG** [anujd64/Thunder#19]
I have my index which has more than 10 shared drives :')). When I added its domain (not subdomain), it crashed. So... I have to add each shared drive manually.
Btw can I request a feature which can download and apply subtile from subsence and opensubtitle?
Thank you for consider this :D have a good day!

**Comment by anujd64** [comment]
Will look into the first issue that might be possible, not so sure about the second one though.

**Comment by chacha121** [comment]
> 



> I have my index which has more than 10 shared drives :')). When I added its domain (not subdomain), it crashed. So... I have to add each shared drive manually. Btw can I request a feature which can download and apply subtile from subsence and opensubtitle? Thank you for consider this :D have a good day!

will you suugest(add) me some shared drives for series and movies

**Comment by KevinNitroG** [comment]
> 

https://github.com/KevinNitroG/Public-Stuff/raw/main/Google_group.txt

You can try it. Some groups may have been deleted because the recent policy of google drive ((: just try it all.

**Comment by chacha121** [comment]
> > 
> 
> https://github.com/KevinNitroG/Public-Stuff/raw/main/Google_group.txt
> 
> You can try it. Some groups may have been deleted because the recent policy of google drive ((: just try it all.

thanks :)
