### ISSUE TITLE
Export index data

### ISSUE THREAD

**Issue by Learner00100** [anujd64/Thunder#22]
1.kindly give a option to export and import manage index data(like we export/import setting in apps), this help to not enter all index one by one ,if we need to use app in another phone.
Just by sharing the export data file, we can import and use on the go.

2.add option to delete particular movie index.

**Comment by anujd64** [comment]
I have been working on import/export of indexes but there are some issues will find a way to implement that.
About the second point could you elaborate?

**Comment by anujd64** [comment]
Export database feature has been added in the latest release and if you do not wish to list a particular movie you can change it's tmdb id to 0!
Hopefully it works for you.

**Comment by Learner00100** [comment]
> 

Thanks for great update
