### ISSUE TITLE
Apps keep stopping

### ISSUE THREAD

**Issue by Moideenmarvan** [anujd64/Thunder#27]
The apps keep stopping even when the app is closed.
![photo_6318916719971775319_x](https://user-images.githubusercontent.com/103314297/202508791-65449d7a-9880-4308-ba6b-361eddb5bb59.jpg)

**Comment by anujd64** [comment]
Have you turned on refresh automatically?
If so try clearing data and don't turn it on this time
the current version has buggy refresh function will be fixed in next update.

**Comment by anujd64** [comment]
You can clear these kind of doubts in the Support topic of the telegram group no need of opening an issue if you don't have a specific bug/error
