### ISSUE TITLE
Support For Secondary Domain

### ISSUE THREAD

**Issue by heypious** [anujd64/Thunder#28]
![image](https://user-images.githubusercontent.com/59928150/204858070-edd48f2b-7707-456c-8868-3df1729ef19f.png)
Google Drive Index has option to use secondary domain instead of primary like how it is in https://rinzry.stream .
So, when this website is added to indexes, the application gets the show name but can't play off it as the stream links are different (only domain is changed).

**Comment by anujd64** [comment]
There's no way to know what the secondary domain is and how the links are formed without consulting the owner so, sorry that is not happening.
