### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by mjain234** [anujd64/Thunder#3]
Facing this error from a while, it happens whenever plays any video, sometimes the video gets played and sometimes it get crashed. It also crashes while switching to another app and coming back to Thunder app.

This is the error:
 FATAL EXCEPTION: Thread-2
Process: com.theflexproject.thunder, PID: 30315
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.theflexproject.thunder.model.File.toString()' on a null object reference
	at com.theflexproject.thunder.fragments.MovieDetailsFragment$3.run(MovieDetailsFragment.java:149)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by anujd64** [comment]
This was happening because the nextPageToken and the pageIndex wasn't being reset while scannig subfolder. Has been fixed.
