### ISSUE TITLE
Add support For google TV

### ISSUE THREAD

**Issue by AmirulAndalib** [anujd64/Thunder#7]
Hi there

This app looks very nice

I wonder if you can Support landscape with correct button mapping for google TV Eg Chromecast Android tv box etc

It would take this app to another level

**Comment by anujd64** [comment]
Right now it does work on Android tvs but experience isn't that great 
will work on making the app more responsive to all screen sizes!

**Comment by AmirulAndalib** [comment]
Ok hope it comes soon 🙂

**Comment by anujd64** [comment]
Hey! The support for Android tvs has been added to the latest release, navigation is possible with a tv remote. You can also export database from your phone and import the same in your tv.
Check the pinned messages in telegram group for details

**Comment by AmirulAndalib** [comment]
> Hey! The support for Android tvs has been added to the latest release, navigation is possible with a tv remote. You can also export database from your phone and import the same in your tv. Check the pinned messages in telegram group for details

Very much thanks dev keep it up 👍
